sudo: false
language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.6
      env: laravel='5.1'
    - php: 5.6
      env: laravel='5.2'
  fast_finish: true

before_install:
  - if [[ $laravel != '5.1' ]]; then pip install --user codecov; fi

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - if [[ $laravel = '5.1' ]]; then travis_retry composer require "illuminate/contracts=5.1.*" --prefer-source --no-interaction; fi
  - if [[ $laravel = '5.2' ]]; then travis_retry composer require "illuminate/contracts=5.2.*" --prefer-source --no-interaction; fi

script:
  - if [[ $laravel != '5.1' ]]; then vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml --exclude-group laravel-5.2; fi
  - if [[ $laravel = '5.1' ]]; then vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml --exclude-group laravel-5.2; fi

after_success:
  - if [[ $laravel != '5.1' ]]; then codecov; fi
