sudo: false
language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - laravel='*'

matrix:
  include:
    - php: 5.6
      env: laravel='5.1'
    - php: 5.6
      env: laravel='5.2'
  fast_finish: true
  allow_failures:
    - php: 7.0

before_script:
  - travis_retry composer self-update
  - if [[ $laravel = '*' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $laravel = '5.1' ]]; then travis_retry composer require "illuminate/contracts=5.1.*" --prefer-source --no-interaction --dev; fi
  - if [[ $laravel = '5.2' ]]; then travis_retry composer require "illuminate/contracts=5.2.*" --prefer-source --no-interaction --dev; fi

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
